# Generated by Django 2.1.1 on 2018-09-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
